name: createTag
on:
  pull_request:
    branches:
      - main
      - engineering
    types: 
      - closed


env: 
  branch_merge: ${{ github.ref_name }}
  branch_source: ${{ github.head_ref }}
  
jobs:
  define-variables:
    if: github.event.pull_request.merged == true  
    runs-on: ubuntu-latest
    steps:
      - name: set-engineering-build
        if: env.branch_merge  == 'engineering'
        run: |
          echo "build_name=Eng${{ env.branch_source }}" >> $GITHUB_ENV
      - name: set-engineering-release
        if: env.branch_merge  == 'engineering'
        run: |
          echo "releaseType=Engineering" >> $GITHUB_ENV
      - name: set-main-build
        if: env.branch_merge  == 'main'
        run: |
          echo "build_name=${{ env.branch_source }}" >> $GITHUB_ENV
      - name: set-main-release
        if: env.branch_merge  == 'main'
        run: |
          echo "releaseType=Commercial" >> $GITHUB_ENV
      - run: env  
      - id: get-buildVersion
        run: |
          id=$(echo ${{steps.get-matlabTag.outputs.id}} | cut -dd -f2)
          echo "::set-output name=id::$id"
      - name: Run other workflow
        run: |
          echo "Run workflow"
          sleep 10s
      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: lhofer12
          repo: test_docs_target
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: Testing.yml        
          client_payload: '{"matlabtag": "${{ env.build_name }}","releaseType":"${{env.releaseType}}", "buildVersion": "${{steps.get-buildVersion.outputs.id}}"}'
  create-tag:
    if: github.event.pull_request.merged == true  
    runs-on: ubuntu-latest
    steps:   
    - name: Create tag
      uses: actions/github-script@v5
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/${{ env.version }}',
            sha: context.sha
            })

   
