name: createTag
on:
  push:
    branches:
      - main
#     tags:
#       - 'release'

env: 
  version: EngBuild9
  message: 'tag created'
  GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
  release_text: 'releases'
  
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: "Change perms on GITHUB_WORKSPACE"
        run: |
          sudo chown -R root:root $GITHUB_WORKSPACE
          sudo chmod -R 0777 $GITHUB_WORKSPACE
      - name: "Create/update tag"
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ env.version }}
          message: ${{ env.message }}
          github_token: ${{ env.GITHUB_TOKEN }}
          
#       - name: Create Release
#         id: create_release
#         uses: actions/create-release@latest
#         with:
#           tag_name: ${{ env.version }}
#           release_name: Release ${{ github.ref }}
#           body: env.release_text
#           draft: false
#           prerelease: false
