name: createTag
on:
  push:
    branches:
      - main

env: 
  version: EngBuild8
  message: 'tag created'
  token:  ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          version: ${{ env.version }}
          message: ${{ env.message }}
          token: ${{ env.token }}
