name: createTag
on:
  push:
    branches:
      - main
#     tags:
#       - 'release'

env: 
  version: EngBuild9
  message: 'tag created'
  GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
  release_text: 'releases'
  
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:        
    - name: Create Tags From
      uses: jaywcjlove/create-tag-action@v1.3.14
      with:
        version: ${{ env.version }}
        token: $${ env.GITHUB_TOKEN }}
          
#       - name: Create Release
#         id: create_release
#         uses: actions/create-release@latest
#         with:
#           tag_name: ${{ env.version }}
#           release_name: Release ${{ github.ref }}
#           body: env.release_text
#           draft: false
#           prerelease: false
