name: createTag
on:
  push:
    branches:
      - main
    tags:
      - 'release'

env: 
  version: EngBuild8
  message: 'tag created'
  GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
  release_text: 'releases'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{env.version}}
          message: ${{env.message}}
#       - name: Create Release
#         id: create_release
#         uses: actions/create-release@latest
#         with:
#           tag_name: ${{ env.version }}
#           release_name: Release ${{ github.ref }}
#           body: env.release_text
#           draft: false
#           prerelease: false
