name: createTag
on:
  push:
    branches:
      - main
#     tags:
#       - 'release'

env: 
  version: EngBuild9
  message: 'tag created'
  GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
  release_text: 'releases'
  
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:   
    - name: Tag snapshot
      uses: tvdias/github-tagger@v0.0.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.version }}
#     - name: Create Tags From
#       uses: jaywcjlove/create-tag-action@main
#       with:
#         test: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'
      
#       uses: laputansoft/github-tag-action@v4.6
#       with:
#         github_token: ${{ env.GITHUB_TOKEN }}
#         tag: ${{ env.version }}
          
#       - name: Create Release
#         id: create_release
#         uses: actions/create-release@latest
#         with:
#           tag_name: ${{ env.version }}
#           release_name: Release ${{ github.ref }}
#           body: env.release_text
#           draft: false
#           prerelease: false
