name: createTag
on:
  push:
    branches:
      - main

env: 
  version: EngBuild8
  message: 'tag created'
  GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        with:
          tag_name: ${{ env.version }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
