name: createTag
on:
  pull_request:
    branches:
      - main
      - engineering
    types: 
      - closed


env: 
  branch_merge: ${{ github.ref_name }}
  branch_source: ${{ github.head_ref }}
  
jobs:
  Explore-GitHub-Actions:
    if: github.event.pull_request.merged == true  
    runs-on: ubuntu-latest
    steps:
      - name: set-engineering-build
        if: ${{ env.branch_merge }} == 'engineering'
        run: |
          echo "build_name=Eng${{ env.branch_source }}" >> $GITHUB_ENV
      - name: set-main-build
        if: ${{ env.branch_merge }} == 'main'
        run: |
          echo "build_name=${{ env.branch_source }}" >> $GITHUB_ENV
      - run: env
      
#   create-tag:
#     runs-on: ubuntu-latest
#     steps:   
#     - name: Create tag
#       uses: actions/github-script@v5
#       with:
#         script: |
#           github.rest.git.createRef({
#             owner: context.repo.owner,
#             repo: context.repo.repo,
#             ref: 'refs/tags/${{ env.version }}',
#             sha: context.sha
#             })
#   run-workflow:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Run other workflow
#       run: |
#         echo "Run workflow"
#         sleep 10s
#     - uses: convictional/trigger-workflow-and-wait@v1.6.1
#       with:
#         owner: lhofer12
#         repo: test_docs_target
#         github_token: ${{ secrets.G_ACCESS_TOKEN }}
#         workflow_file_name: Testing.yml
#         client_payload: '{"version": "${{ env.version }}"}'
# #         version: "${{ env.version }}"
# #         client_payload: '{"inputs":{"version": "${{ env.version }}" }}'

