name: Compile code base version and upload to azure blob storage
on:
  push:
    tags:
      - '*'


jobs:
  runs-on: ubuntu-latest
  run: echo event name ${{ github.event.name }}
  run: echo event actor id ${{ github.event.actor.id }} 
  run: echo event tag ${{ github.event.tag }} 
